import uuid

class Customer:
    """Represents a customer with an ID, name, and email or phone number"""
    
    def __init__(self, cust_name: str, cust_email: str = "", cust_phone: str = "") -> None:
        """
        Initialise a new Customer object

        :param cust_name: Name of the customer (does not need to be unique, differnt customers can have the same name)
        :param cust_email: Contact email address of the customer
        :param cust_phone: Contact phone number of the customer
        :raises ValueError: If there is not at least one of cust_email or cust_phone
        """
        
        if not cust_email and not cust_phone:
            raise ValueError("Please provide at least an email or a phone number")
        
        # Autogenerated ID for now to keep it simple
        self.__cust_id = uuid.uuid4()
        self.__cust_name = cust_name
        self.__cust_email = cust_email if cust_email else None
        self.__cust_phone = cust_phone if cust_phone else None
        
    # ---------- Getters and Setters ----------
    
    # Assuming Customer details are not updated after creation
        
    @property
    def cust_id(self) -> uuid.UUID:
        """Get the unique customer ID"""
        return self.__cust_id

    @property
    def cust_name(self) -> str:
        """Get the customer name"""
        return self.__cust_name

    @property
    def cust_email(self) -> str:
        """Get the customer email"""
        return self.__cust_email

    @property
    def cust_phone(self) -> str:
        """Get the customer phone number"""
        return self.__cust_phone
        
    # ---------- Methods ----------
        
    def __str__(self) -> str:
        """Returns a readable string of the customer details"""
        return (
            "Customer ID: {}, Customer Name: {}, Customer Email: {},"
            " Customer Phone Number: {}"
            .format(
                self.__cust_id, self.__cust_name,
                self.__cust_email, self.__cust_phone,
            )
        )