import uuid
from typing import Literal, get_args

# Assuming there will be no new categories for now
PlantCategory = Literal["trees and shrubs", "perennials", "pot plants", "vegetable seedlings"]

class Plant:
    """Represents a plant with an ID, category, price and stock level"""
    
    def __init__(self, plant_name: str, plant_category: PlantCategory, plant_price: float, plant_stock: int) -> None:
        """
        Initialise a new Plant object

        :param plant_name: Name of the plant (does not need to be unique, same name can have different price/stock)
        :param plant_category: Category of the plant, must be one of the four allowed PlantCategory values
        :param plant_price: Price of the plant, must be greater than 0
        :param plant_stock: Stock on hand for this plant, must be 0 or more
        :raises ValueError: If category is invalid, price is not greater than 0, or stock is negative
        """
        
        # Assuming a name will be given and data types will be correct for now
        if plant_category not in get_args(PlantCategory):
            raise ValueError(f"Plant category must be one of {get_args(PlantCategory)}")
        if plant_price <= 0:
            raise ValueError("Plant price must be greater than 0")
        if plant_stock < 0:
            raise ValueError("Plant stock must be 0 or more")
        
        # Autogenerated ID for now to keep it simple
        self.__plant_id = uuid.uuid4()
        self.__plant_name = plant_name
        self.__plant_category = plant_category
        self.__plant_price = plant_price
        self.__plant_stock = plant_stock
        
    # ---------- Getters and Setters ----------
        
    @property
    def plant_id(self) -> uuid.UUID:
        """Get the unique plant ID"""
        return self.__plant_id

    @property
    def plant_name(self) -> str:
        """Get the plant name"""
        return self.__plant_name

    @property
    def plant_category(self) -> PlantCategory:
        """Get the plant category"""
        return self.__plant_category

    @property
    def plant_price(self) -> float:
        """Get the plant price"""
        return self.__plant_price
    
    # Assuming only stock and price can be changed once a Plant object is created 
    @plant_price.setter
    def plant_price(self, value: float) -> None:
        """
        Update the price of the plant

        :param value: New price, must be greater than 0
        :raises ValueError: If value is not greater than 0
        """
        if value <= 0:
            raise ValueError("Plant price must be greater than 0")
        self.__plant_price = value
    
    @property
    def plant_stock(self) -> int:
        """Get the current stock of the plant"""
        return self.__plant_stock
    
    # Assuming only stock and price can be changed once a Plant object is created    
    @plant_stock.setter
    def plant_stock(self, value: int) -> None:
        """
        Directly set the plant stock level

        :param value: New stock level, must be 0 or more
        :raises ValueError: If value is negative
        """
        if value < 0:
            raise ValueError("Plant stock must be 0 or more")
        self.__plant_stock = value
        
    # ---------- Methods ----------

    def check_stock(self, quantity: int) -> bool:
        """
        Check whether there is enough stock to supply an order

        :param quantity: Quantity being requested
        :return: True if stock is greater than or equal to quantity, else False
        """
        return self.__plant_stock >= quantity

    def reduce_stock(self, quantity: int) -> None:
        """
        Reduce stock when an order goes through. Stock can never be below zero

        :param quantity: Quantity to remove from stock
        :raises ValueError: If quantity is not positive, or there isn't enough stock to cover it
        """
        if quantity <= 0:
            raise ValueError("Quantity to reduce must be greater than 0")
        if not self.check_stock(quantity):
            raise ValueError(f"Insufficient stock: only {self.__plant_stock} available")
        self.__plant_stock -= quantity

    def restore_stock(self, quantity: int) -> None:
        """
        Return stock when a pending order is cancelled

        :param quantity: Quantity to add back
        :raises ValueError: If quantity is not positive
        """
        if quantity <= 0:
            raise ValueError("Quantity to restore must be greater than 0")
        self.__plant_stock += quantity
        
    def __str__(self) -> str:
        """Returns a readable string of the plant details"""
        return (
            "Plant ID: {}, Plant Name: {}, Plant Category: {},"
            " Plant Price: {}, Plant Stock: {}"
            .format(
                self.__plant_id, self.__plant_name,
                self.__plant_category, self.__plant_price,
                self.__plant_stock
            )
        )